version: '3'

# networks:
#   app-net:
#     driver: bridge

services:
  pg:
    image: postgres:13.3-alpine
    container_name: pg
    environment:
      POSTGRES_PASSWORD: kf_db_password
      POSTGRES_USER: kf_db_user
      POSTGRES_DB: kasefile
    restart: unless-stopped
    # networks:
    #   - app-net
    ports:
      - '5432:5432'

  api:
    image: node:18
    container_name: api
    # command: bash -c "npm install && npm run dev"
    command: 'tail -f /dev/null'
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./app/api:/app/kf-backend/app/api
      - ./app/auth:/app/kf-backend/app/auth
      - ./app/db:/app/kf-backend/app/db
      - ./app/utility:/app/kf-backend/app/utility
      - ./app/favicon.ico:/app/kf-backend/favicon.ico
      - ./app/globals.css:/app/kf-backend/globals.css
      - ./app/layout.tsx:/app/kf-backend/layout.tsx
      - ./app/page.module.css:/app/kf-backend/page.module.css
      - ./app/page.tsx:/app/kf-backend/page.tsx
      # Root of the project
      - ./public:/app/kf-backend/public
      - ./.next:/app/kf-backend/.next
      - ./node_modules:/app/kf-backend/node_modules
      - ./jest.config.ts:/app/kf-backend/jest.config.ts
      - ./next-env.d.ts:/app/kf-backend/next-env.d.ts
      - ./next.config.mjs:/app/kf-backend/next.config.mjs
      - ./package-lock.json:/app/kf-backend/package-lock.json
      - ./package.json:/app/kf-backend/package.json
      - ./tsconfig.json:/app/kf-backend/tsconfig.json
      - ./.env:/app/kf-backend/.env
